package com.potato.study.leetcode.p0389;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * @author liuzhao11
 * 
 *       389. Find the Difference
 * 
 *     Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 *         
 *         思路：
 *        
 *         
 */
public class Solution{
	
	public char findTheDifference(String s, String t) {
		Map<Character, Integer> map = new HashMap<>();
		for(char ch : s.toCharArray()) {
			if(map.containsKey(ch)) {
				map.put(ch, map.get(ch) + 1);
			} else {
				map.put(ch, 1);
			}
		}
		for(char ch : t.toCharArray()) {
			if(map.containsKey(ch)) {
				map.put(ch, map.get(ch) - 1);
				if(map.get(ch) < 0) {
					return ch;
				}
			} else {
				return ch;
			}
		}
		return ' ';
	}
	
	
	public static void main(String[] args) {
		Solution solution = new Solution();
		String s = "abcd";
		String t = "abcde";
		char ch = solution.findTheDifference(s, t);
		System.out.println(ch);
	}
}

